export 'package:flutter/material.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_storage/firebase_storage.dart';
export 'package:firebase_database/firebase_database.dart'
    hide Transaction, Query, TransactionHandler;
export 'package:dropdown_search/dropdown_search.dart'
    hide ErrorBuilder, defaultScrollNotificationPredicate;
export 'package:provider/provider.dart';
export 'package:get/get.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:ionicons/ionicons.dart';
export 'package:line_icons/line_icons.dart';
export 'package:scroll_snap_list/scroll_snap_list.dart';
export 'package:animated_text_kit/animated_text_kit.dart';
export 'package:card_swiper/card_swiper.dart';

export 'package:velocity_x/velocity_x.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:image_picker/image_picker.dart';
export 'package:introduction_screen/introduction_screen.dart';
export 'package:flutter_spinkit/flutter_spinkit.dart';
export 'package:heal_the_health_app/splash/Splash_screen.dart';
export 'package:heal_the_health_app/widgets/chip.dart';
export 'package:heal_the_health_app/widgets/round_button.dart';
export 'package:heal_the_health_app/utils/utils.dart';
export 'package:heal_the_health_app/authentication/login/login.dart';
export 'package:heal_the_health_app/authentication/sign_up/sign_up.dart';
export 'package:flutter/services.dart';
export 'package:heal_the_health_app/providers/auth_notifier.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:heal_the_health_app/models/patient.dart';
export 'package:heal_the_health_app/authentication/service/database.dart';
export 'package:heal_the_health_app/splash/splash_services.dart';
export 'package:heal_the_health_app/authentication/service/auth.dart';
export 'package:heal_the_health_app/Routes/route_names.dart';
export 'package:heal_the_health_app/Routes/routes.dart';
export 'package:heal_the_health_app/home/colors.dart';
export 'package:heal_the_health_app/home/medical_conditions.dart';
export 'package:heal_the_health_app/onboarding/onboard.dart';
export 'package:heal_the_health_app/widgets/appbar.dart';
export 'package:heal_the_health_app/authentication/login/doctor_login.dart';
export 'package:heal_the_health_app/authentication/sign_up/doctor_form.dart';
export 'package:heal_the_health_app/authentication/sign_up/doctor_sign_up.dart';
export 'package:heal_the_health_app/authentication/sign_up/user_form.dart';
export 'package:heal_the_health_app/home/doctor/list_patients.dart';
export 'package:heal_the_health_app/main.dart';
export 'package:heal_the_health_app/home/patient/add_medical_conditions.dart';
export 'package:heal_the_health_app/authentication/login/login_phone.dart';
export 'package:heal_the_health_app/authentication/service/forgot_password.dart';
export 'package:heal_the_health_app/authentication/service/verify_code.dart';
export 'package:heal_the_health_app/home/doctor/add_patients.dart';
export 'package:heal_the_health_app/home/patient/doctor_details.dart';
export 'package:heal_the_health_app/home/doctor/patient_details_sheet.dart';
export 'package:heal_the_health_app/providers/user_shared_pref.dart';
export 'package:heal_the_health_app/home/patient/home_page.dart';
export 'package:google_nav_bar/google_nav_bar.dart';
export 'package:heal_the_health_app/home/patient/user_page0.dart';
export 'package:heal_the_health_app/home/patient/user_profile.dart';
export 'package:heal_the_health_app/ml_models/result_symptoms.dart';
export 'package:heal_the_health_app/home/patient/health_needs.dart';
export 'package:heal_the_health_app/home/patient/diary.dart';
export 'package:heal_the_health_app/home/patient/medical_records.dart';
export 'package:heal_the_health_app/ml_models/list_models.dart';
export 'package:heal_the_health_app/home/patient/add_doctors.dart';
export 'package:heal_the_health_app/home/disease_details.dart';
export 'package:heal_the_health_app/home/appointment/appointments.dart';
export 'package:heal_the_health_app/home/patient/insurance.dart';
export 'package:heal_the_health_app/ml_models/symptoms.dart';
export 'package:heal_the_health_app/models/appointment.dart';
export 'package:heal_the_health_app/home/appointment/backend.dart';
export 'package:heal_the_health_app/home/appointment/booking_page.dart';
//for diary
export 'package:heal_the_health_app/home/diary/main_diary.dart';
export 'package:heal_the_health_app/home/diary/add_buttun.dart';
export 'package:heal_the_health_app/home/diary/custom_rect.dart';
export 'package:heal_the_health_app/home/diary/diary_list.dart';
export 'package:heal_the_health_app/home/diary/hero_dialog.dart';

export 'package:intl/intl.dart' hide TextDirection;
export 'dart:io' hide HeaderValue, interface;

export 'package:heal_the_health_app/models/disease.dart';
export 'package:heal_the_health_app/models/symptom.dart';
export 'package:heal_the_health_app/models/doctor.dart';
export 'package:heal_the_health_app/home/diary/diary_model.dart';

export 'package:heal_the_health_app/constants/disease_list.dart';
export 'package:heal_the_health_app/constants/symptoms_list.dart';

const regular = 'sans_regular';
const bold = 'sans_bold';
const semibold = 'sans_semibold';
